parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3306'
    database_name: factsys
    database_user: factsys
    database_password: factsys
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: es
    secret: 1bb2f0b114850db1f0a63c5d1b00c35833c6c2bd
    database_path: null
